### ISSUE TITLE
bootstrap script creates a link to a repository with capital letters

### ISSUE THREAD

**Issue by fluff79** [openfisca/country-template#84] opened 2020-02-01 07:29 UTC
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
I created a repo on GitHub called:
[https://github.com/fluff79/openfisca-jersey](https://github.com/fluff79/openfisca-jersey)
this uses lower case like France and the folder on my computer.

After running the bootstrap script, I then type
`git remote add origin https://github.com/fluff79/openfisca-jersey`

the terminal tells me the "remote origin already exists".

The script has created a reference pointing to (notice the capital letters) :
https://github.com/fluff79/OpenFisca-Jersey.git

You should therefore tell people what to call their new repository in your documentation, if this is kept in the script, or take it out of the script and provide the instructions in the documentation of how to "add origin" etc.

and say the next step is
`git push -u origin master`

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Business expert _(I create tests and model legislation)_.
- Commenter _(I make data visualisations)_.

**Comment by Br3nda** [comment] 2020-02-01 22:27
Try
`git remote rm origin` then try that step again.

**Comment by maukoquiroga** [comment] 2020-02-11 00:03
Bravo @fluff79 for the new country package! 👍

I don't really know what the capital letters ...

**Comment by maukoquiroga** [comment] 2020-02-11 00:09
Thanks @fluff79 the script is proving quite a challenge, lots of assumptions I guess.

Regarding the capital letters, I guess it is meant for the README.md and so on.

Whether the reference to the git repository is capital or not, I think it has no effect you confirm?

**Comment by fluff79** [comment] 2020-02-13 08:05
Thanks.  I think the error i got was because the script included repository reference with capital letters. When I removed and added origin with lowercase it worked. So I think capital letters matter.  Am i wrong? I will check later.

**Comment by maukoquiroga** [comment] 2020-11-08 09:50
Hello @fluff79 ,

I'm running the following

```
me@diotimac:~/openfisca > unzip country-template-master.zip
me@diotimac:~/openfisca > cd country-template-master
me@diotimac:~/openfisca/country-template-master[master] > export COUNTRY_NAME=Chile
me@diotimac:~/openfisca/country-template-master[master] > export REPOSITORY_URL=https://github.com/YOUR_ORGANISATION/OpenFisca-$COUNTRY_NAME

...

me@diotimac:~/openfisca/country-template-master[master] > git config --get remote.origin.url
https://github.com/YOUR_ORGANISATION/OpenFisca-Chile.git
```

Which is the intended behaviour.

**Comment by maukoquiroga** [comment] 2020-11-08 09:53
We tried to make it clearer here #81 so closing for now, please do not hesitate to reopen if it is not what you meant or expect. Have a great day!

**Closed by maukoquiroga** 2020-11-08 09:53 UTC
Labels: kind:documentation
